AWSTemplateFormatVersion: 2010-09-09
Description: Shared resources for the RJC AWS account.
Resources:
   ApiCloudWatchRole:
      Type: 'AWS::IAM::Role'
      Properties:
         RoleName: api-gateway-cloudwatch-write-access
         Description: Allows API Gateway to write to CloudWatch logs, across all APIs.
         AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
               - Effect: Allow
                 Principal:
                    Service:
                       - apigateway.amazonaws.com
                 Action:
                    - 'sts:AssumeRole'
         ManagedPolicyArns:
            - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
   ApiLogAccount:
      Type: 'AWS::ApiGateway::Account'
      DeletionPolicy: Retain
      Properties:
         CloudWatchRoleArn: !GetAtt ApiCloudWatchRole.Arn
